CM.make("$/basis.cm");
CM.make("$/ml-yacc-lib.cm");
use "rational.sml";
use "AST.sml";
use "parser.yacc.sig";
use "parser.yacc.sml";
use "lexer.lex.sml";
use "glue.sml";
Control.Print.printLength := 1000;
Control.Print.printDepth := 1000; 
Control.Print.stringDepth := 1000; 